apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
spec:
  selector: 
    app: jenkins-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
#spec:
#  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: 8080
#  selector:
#    app: jenkins-server
#  sessionAffinity: None
#  type: LoadBalancer