name: Plugins Update
on:
  push:
    branches:
      - main
      - feature/*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make plugins.sh executable
        run: |
          chmod +x ./plugins.sh
      - name: Run plugins update
        run: |
          ./plugins.sh
